const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('scriptify', {
  mcpStatus: () => ipcRenderer.invoke('mcp-status'),
  listLocal: () => ipcRenderer.invoke('list-local-scripts'),
  readLocal: (filename) => ipcRenderer.invoke('read-local-script', filename),
  saveLocal: (filename, code) => ipcRenderer.invoke('save-local-script', filename, code),
  listMcp: () => ipcRenderer.invoke('list-mcp-scripts'),
  pushToMcp: (filename) => ipcRenderer.invoke('push-to-mcp', filename),
  downloadFromMcp: (title) => ipcRenderer.invoke('download-from-mcp', title),
  execute: (code) => ipcRenderer.invoke('execute-script', code),
  fetchDocs: () => ipcRenderer.invoke('fetch-docs'),
  searchDocs: (query) => ipcRenderer.invoke('search-docs', query),
  getWatch: () => ipcRenderer.invoke('get-watch'),
  setWatch: (enabled) => ipcRenderer.invoke('set-watch', enabled),
  onWatchPush: (cb) => ipcRenderer.on('watch-push', (_e, data) => cb(data)),
  onLibraryChanged: (cb) => ipcRenderer.on('library-changed', (_e, data) => cb(data)),
  deleteLocal: (filename) => ipcRenderer.invoke('delete-local-script', filename),
  renameLocal: (filename, newName) => ipcRenderer.invoke('rename-local-script', filename, newName),
  exportToDisk: (filename) => ipcRenderer.invoke('export-to-disk', filename),
  getRepos: () => ipcRenderer.invoke('get-repos'),
  addRepo: (url) => ipcRenderer.invoke('add-repo', url),
  removeRepo: (url) => ipcRenderer.invoke('remove-repo', url),
  listCommunity: () => ipcRenderer.invoke('list-community-scripts'),
  installCommunity: (script) => ipcRenderer.invoke('download-community-script', script),
  saveCommunity: (script) => ipcRenderer.invoke('save-community-script', script),
  openUrl: (url) => ipcRenderer.send('open-url', url),
  getFavorites: () => ipcRenderer.invoke('get-favorites'),
  toggleFavorite: (stem) => ipcRenderer.invoke('toggle-favorite', stem),
  renderPreview: () => ipcRenderer.invoke('render-active-preview'),
  getUpdateRepo: () => ipcRenderer.invoke('get-update-repo'),
  setUpdateRepo: (repo) => ipcRenderer.invoke('set-update-repo', repo),
  checkUpdates: () => ipcRenderer.invoke('check-updates'),
  aiStatus: () => ipcRenderer.invoke('ai-status'),
  aiSaveSettings: (settings) => ipcRenderer.invoke('ai-save-settings', settings),
  aiClearKey: () => ipcRenderer.invoke('ai-clear-key'),
  aiGenerate: (payload) => ipcRenderer.invoke('ai-generate', payload),
  aiFix: (payload) => ipcRenderer.invoke('ai-fix', payload)
});
